apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-redis
  name: redis-service
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  clusterIP: None
  selector:
    app: app-redis
    statefulset.kubernetes.io/pod-name: app-redis-0