apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/g3devopssavages/wolt-registry/data"
