---
apiVersion: "batch/v1beta1"
kind: "CronJob"
metadata:
  name: "kp-registry-cj"
  labels:
    app: "kp-registry-cj"
spec:
  schedule: "0 1 * * *"  # Daily at 1am
  jobTemplate:
    spec:
      template:
        spec:          
         containers:
         - name: "registrycontainer"
           image: "registry:2"
           imagePullPolicy: Always
           ports:
           - containerPort: 5000
             name: "registry-port"
           volumeMounts:
           - name: config-volume
             mountPath: /etc/docker/registry/config.yml
             subPath: config.yml
           - name: registry-pv-storage
             mountPath: "/var/lib/registry" 
           - name: htpasswd-volume
             mountPath: "/registry_auth"
             readOnly: true
           env:
           - name: REGISTRY_REDIS_ADDR
             value: "redis-service"  
           - name: REGISTRY_HTTP_ADDR
             value: ":5000"
           - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
             value: "/var/lib/registry" 
           - name: REGISTRY_AUTH
             value: "htpasswd"
           - name: REGISTRY_AUTH_HTPASSWD_REALM
             value: "Authentication required"   
           - name: REGISTRY_AUTH_HTPASSWD_PATH
             value: '/registry_auth/htpasswd'
           command: ["/bin/registry", "garbage-collect","/etc/docker/registry/config.yml"]
         restartPolicy: OnFailure
         volumes:
          - name: config-volume
            configMap:
              name: registry-config-cm
          - name: registry-pv-storage
            persistentVolumeClaim:
              claimName: registry-pv-claim
          - name: htpasswd-volume
            secret:
              secretName: registry-auth
